[package]
name = "lazyoc"
version = "0.1.0"
authors = ["Yoandy Rodriguez <yoandy.rmartinez@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.21.0"

[dependencies.tui]
version = "0.16.0"
default-features = false
features = ["crossterm"]
